### ISSUE TITLE
Git-xargs execution hangs with no error message

### ISSUE THREAD

**Issue by akohjialing** [gruntwork-io/git-xargs#97]
Upon execution, git-xargs hangs with no error message:
![image](https://user-images.githubusercontent.com/82496019/196382560-956e9685-00c0-4662-bb11-259ac7a3a797.png)

This is the command I'm trying to execute in the shell script (Token, org name and repo name have been removed while reporting this issue):

export GITHUB_TOKEN=XXX

git-xargs \
  --loglevel DEBUG \
  --dry-run \
  --branch-name testing \
  --commit-message "Creation File Test" \
  --repo <_org-name_>/<_repo-name_> \
  touch hello-world.txt

Please advise what the issue might be, thank you.

**Comment by zackproser** [comment]
Hi @akohjialing - which version of git-xargs are you running? Does this occur when you use the latest release?

What happens when you run just your script alone, outside of git-xargs? Could you try using [any of these flags](https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_02_03.html) to debug your script and see if something is causing it to hang?

**Comment by zackproser** [comment]
Given that I'm pretty confident I know this was caused by a bad release version in the past, and I'm pretty sure that this issue has since been fixed, I'm going to close this out due to inactivity. If you are able to reproduce with a minimal test case and version feel free to re-open. Thanks!
